// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-dfSeSY9tqSaywXoHt-GfElN4J3xt9_0',
    appId: '1:682344994266:web:4c60f2447e6574e69f9ce3',
    messagingSenderId: '682344994266',
    projectId: 'my-firebase-project-481b1',
    authDomain: 'my-firebase-project-481b1.firebaseapp.com',
    storageBucket: 'my-firebase-project-481b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4JZD9TfrgSNtQE6P0qK74DpU4poMQGA8',
    appId: '1:682344994266:android:20de6f95794868fc9f9ce3',
    messagingSenderId: '682344994266',
    projectId: 'my-firebase-project-481b1',
    storageBucket: 'my-firebase-project-481b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi0BJ82OziqmYYgEcDlumSOOwX_nSf7uA',
    appId: '1:682344994266:ios:2841023b0ad29ef39f9ce3',
    messagingSenderId: '682344994266',
    projectId: 'my-firebase-project-481b1',
    storageBucket: 'my-firebase-project-481b1.appspot.com',
    iosClientId: '682344994266-9kb2v6ah0vb14bm1rf4cm8jukbqjpogf.apps.googleusercontent.com',
    iosBundleId: 'com.example.fortuneRoomBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi0BJ82OziqmYYgEcDlumSOOwX_nSf7uA',
    appId: '1:682344994266:ios:2841023b0ad29ef39f9ce3',
    messagingSenderId: '682344994266',
    projectId: 'my-firebase-project-481b1',
    storageBucket: 'my-firebase-project-481b1.appspot.com',
    iosClientId: '682344994266-9kb2v6ah0vb14bm1rf4cm8jukbqjpogf.apps.googleusercontent.com',
    iosBundleId: 'com.example.fortuneRoomBookingApp',
  );
}
